name: PyPI Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Verify version matches tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        pip install setuptools
        SETUP_VERSION=$(python setup.py --version)
        if [ "$TAG_VERSION" != "$SETUP_VERSION" ]; then
          echo "Version mismatch: Tag v$TAG_VERSION != setup.py $SETUP_VERSION"
          exit 1
        fi
        echo "Version match: $TAG_VERSION"

    - name: Build package
      run: |
        pip install build twine
        python -m build

    - name: Check distribution
      run: twine check dist/*

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          **New Release: ${{ github.ref_name }}**

          ## Installation
          ```bash
          pip install --upgrade wbh-campus-scraper
          ```

          ## Tested Python Versions
          - Python 3.8, 3.9, 3.10, 3.11, 3.12, 3.13

          ## Changes
          See commit history for detailed changes.
        draft: false
        prerelease: false