name: Update Formula

on:
  push:
    tags: ['v*']

jobs:
  update-formula:
    name: Update wbh-campus-scraper formula
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update Homebrew Formula
      env:
        GITHUB_TOKEN: ${{ secrets.TAP_UPDATE_TOKEN }}
      run: |
        echo "Updating Homebrew formula..."

        # Get version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Version: $VERSION"

        # Clone homebrew-tap repository
        git clone https://$GITHUB_TOKEN@github.com/jonaskern-dev/homebrew-tap.git tap-repo
        cd tap-repo

        # Configure git
        git config user.email "action@github.com"
        git config user.name "GitHub Action"

        # Download and calculate SHA256
        TARBALL_URL="https://github.com/jonaskern-dev/wbh-campus-scraper/archive/refs/tags/v${VERSION}.tar.gz"
        echo "Downloading: $TARBALL_URL"
        wget -O tarball.tar.gz "$TARBALL_URL"
        SHA256=$(sha256sum tarball.tar.gz | cut -d' ' -f1)
        echo "New SHA256: $SHA256"
        rm tarball.tar.gz

        # Update formula file
        echo "Updating Formula/wbh-campus-scraper.rb"
        sed -i "s|archive/refs/tags/v.*\.tar\.gz|archive/refs/tags/v${VERSION}.tar.gz|" Formula/wbh-campus-scraper.rb
        sed -i "s/sha256 \".*\"/sha256 \"${SHA256}\"/" Formula/wbh-campus-scraper.rb

        # Verify changes
        echo "Updated formula:"
        grep -A2 -B2 "url\|sha256" Formula/wbh-campus-scraper.rb

        # Test formula syntax
        ruby -c Formula/wbh-campus-scraper.rb
        echo "Formula syntax is valid"

        # Commit and push if there are changes
        if git diff --quiet Formula/wbh-campus-scraper.rb; then
          echo "No changes to commit"
        else
          git add Formula/wbh-campus-scraper.rb
          git commit -m "wbh-campus-scraper: update to ${VERSION}

- Update URL to v${VERSION}
- Update SHA256 hash
- Auto-generated by GitHub Actions"
          git push origin main
          echo "Successfully updated formula to version ${VERSION}"
        fi